name: CI/CD

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.yarn
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Eslint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
