name: CI/CD

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  ci:
    name: ${{ matrix.os }} - Node ${{ matrix.node }} - ${{ matrix.task }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16]
        task: [Find missing dependencies, Lint, Format, Build and Test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set BASE and HEAD
        uses: nrwl/nx-set-shas@v3
        with:
          event: ${{ github.event_name }}
          base: ${{ github.base_ref }}
          head: ${{ github.head_ref }}

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Find missing dependencies
        if: matrix.task == 'Find missing dependencies'
        run: node scripts/findMissingDependencies.js

      - name: Run ESLint on Affected Projects
        if: matrix.task == 'Lint'
        run: yarn nx affected --target=lint --base=$BASE --head=$HEAD
        continue-on-error: true

      - name: Annotate ESLint Results
        if: matrix.task == 'Lint'
        uses: ataylorme/eslint-annotate-action@1.2.0
        if: always()
        continue-on-error: true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'

      - name: Run Prettier on Affected Projects
        if: matrix.task == 'Format'
        run: yarn nx affected --target=format:check --base=$BASE --head=$HEAD

      - name: Build and Test Affected Projects
        if: matrix.task == 'Build and Test'
        run: |
          yarn nx affected --target=build --base=$BASE --head=$HEAD
          yarn nx affected --target=test --base=$BASE --head=$HEAD