name: CI/CD

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - main
      - beta
      - alpha

env:
  BASE_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || 'main' }}

jobs:
  find_dependencies:
    name: Find missing dependencies - ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch Base Branch
        if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin ${{ env.BASE_BRANCH }}

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Find missing dependencies
        run: node scripts/findMissingDependencies.js

  lint_and_format:
    name: Lint and Format - ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch Base Branch
        if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=5 origin ${{ env.BASE_BRANCH }}

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run ESLint on Affected Projects
        run: yarn nx affected --target=lint --base=origin/${{ env.BASE_BRANCH }} --head=HEAD
        continue-on-error: true

      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        continue-on-error: true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'

      - name: Run Prettier on Affected Projects
        run: yarn nx affected --target=format:check --base=origin/${{ env.BASE_BRANCH }} --head=HEAD

  build_and_test:
    name: Build and Test - ${{ matrix.os }} - Node 16
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch Base Branch
        run: git fetch --no-tags --prune --depth=5 origin ${{ env.BASE_BRANCH }}

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build and Test Affected Projects
        run: |
          yarn nx affected --target=build --base=origin/${{ env.BASE_BRANCH }} --head=HEAD
          yarn nx affected --target=test --base=origin/${{ env.BASE_BRANCH }} --head=HEAD
